// Code generated by Slice Machine. DO NOT EDIT.

import Articles from './Articles';
import Categories from './Categories';
import Hero from './Hero';
import ImageInPost from './ImageInPost';
import Quote from './Quote';
import Reply from './Reply';
import Text from './Text';

export {
	Articles,
	Categories,
	Hero,
	ImageInPost,
	Quote,
	Reply,
	Text,
};

export const components = {
	articles: Articles,
	categories: Categories,
	hero: Hero,
	image_in_text: ImageInPost,
	quote: Quote,
	reply: Reply,
	text: Text,
};
